blank_issues_enabled: true
contact_links:
  - name: Discussions
    url: https://github.com/jcearnal/magnetile/discussions
    about: Ask questions or share ideas that aren't bugs or feature requests
